/**
 * generated by Xtext 2.25.0
 */
package dk.sdu.bdd.xtext.tests;

import com.google.inject.Inject;
import dk.sdu.bdd.xtext.bddDsl.Model;
import org.eclipse.xtext.testing.InjectWith;
import org.eclipse.xtext.testing.extensions.InjectionExtension;
import org.eclipse.xtext.testing.util.ParseHelper;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;

@ExtendWith(InjectionExtension.class)
@InjectWith(BddDslInjectorProvider.class)
@SuppressWarnings("all")
public class BddDslParsingTest {
  @Inject
  private ParseHelper<Model> parseHelper;

  @Test
  public void loadModel() {
    throw new Error("Unresolved compilation problems:"
      + "\nno viable alternative at input \'Â\'"
      + "\nmismatched input \'»\'\'\'\' expecting \'}\'"
      + "\nThe method or field Â is undefined");
  }
}
